# This file was generated by GoReleaser. DO NOT EDIT.
cask "finops-guard" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "e4cc7229e475bf07b9ac06a3d806c71b5b86639d95037ba7f530afe4b2d0ed60"
      url "https://github.com/srikalachallagundla32-cloud/finops-guard/releases/download/v#{version}/finops-guard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d405db7943f84f3db8c10ae293bb3c140969e916553138cc3da03346883e43fb"
      url "https://github.com/srikalachallagundla32-cloud/finops-guard/releases/download/v#{version}/finops-guard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cdc18992fe72b40b1b73dcde18cd21edb78fe1f5cd389a2194b31107fcc35567"
      url "https://github.com/srikalachallagundla32-cloud/finops-guard/releases/download/v#{version}/finops-guard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "df3ee2ba9590fa43b17116dfd4d424df85f7381ef138593114c0989ca39b69be"
      url "https://github.com/srikalachallagundla32-cloud/finops-guard/releases/download/v#{version}/finops-guard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "finops-guard"
  desc "FinOps guardrails for codebases: static loop-cost detection, an animated TUI, and GitHub PR cost cards."
  homepage "https://github.com/srikalachallagundla32-cloud/finops-guard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "finops-guard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/finops-guard"]
    end
  end

  # No zap stanza required

end
