# This file was generated by GoReleaser. DO NOT EDIT.
cask "finops-guard" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "16583f5fd56523ce9469e382d38171e65a1f46c91bae256f60c6509cb1a85444"
      url "https://github.com/srikalachallagundla32-cloud/finops-guard/releases/download/v1.0.1/finops-guard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "670cb7ca888dd8ec8c875344c3a0c1e0132b0d2c9935b286091635163dc99283"
      url "https://github.com/srikalachallagundla32-cloud/finops-guard/releases/download/v1.0.1/finops-guard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc87d45e03d9f6aec3493da83043788cc71c1558eea96a184ba620b30cc1a86d"
      url "https://github.com/srikalachallagundla32-cloud/finops-guard/releases/download/v1.0.1/finops-guard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "96f232cd22118cbe2c18db7b4c37217f26b0c4fcf3e70cdca6b8e74e88d0954f"
      url "https://github.com/srikalachallagundla32-cloud/finops-guard/releases/download/v1.0.1/finops-guard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "finops-guard"
  desc "FinOps guardrails for codebases: static loop-cost detection, an animated TUI, and GitHub PR cost cards."
  homepage "https://github.com/srikalachallagundla32-cloud/finops-guard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "finops-guard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/finops-guard"]
    end
  end
end
