# This file was generated by GoReleaser. DO NOT EDIT.
cask "finops-guard" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "c57b6ccba62e04520d08c8484e73affb16232da6c454ea96053c07af33031631"
      url "https://github.com/srikalachallagundla32-cloud/finops-guard/releases/download/v1.0.0/finops-guard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3f20ea21984f9b2d35299ac6117708c8f1228267f8c4ad716d46a6166abdda5"
      url "https://github.com/srikalachallagundla32-cloud/finops-guard/releases/download/v1.0.0/finops-guard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "10e8b0d853992c6f63e8e6fef53a754b6ceb1cafa7f3b671a170690271cbc1e7"
      url "https://github.com/srikalachallagundla32-cloud/finops-guard/releases/download/v1.0.0/finops-guard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d28c431a73c72baff69c67362c55b948e47ddd32f951668298e85de19009bdb6"
      url "https://github.com/srikalachallagundla32-cloud/finops-guard/releases/download/v1.0.0/finops-guard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "finops-guard"
  desc "FinOps guardrails for codebases: static loop-cost detection, an animated TUI, and GitHub PR cost cards."
  homepage "https://github.com/srikalachallagundla32-cloud/finops-guard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "finops-guard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/finops-guard"]
    end
  end
end
